### ISSUE TITLE
Guidebook contains a broken link

### ISSUE THREAD

**Issue by jash-bansal** [JimTheMan/Triplex-Testing-Guidebook#1]
The facebook group referenced in the guidebook contains a broken link. 

[https://www.facebook.com/triplextesting](url)

**Comment by JimLynchCodes** [comment]
Thanks jash!

Good catch :)

I was forgetting the /groups/.

Now updated to the correct link:
https://www.facebook.com/groups/triplextesting/

Feel free to join the group and let me know what you think about triplex testing, good or bad! 👍
